#!/usr/bin/env python3
"""Offline, post-hoc one/two-horizon gate sensitivity on verified v3 forecasts.

Window labels remain the official two-horizon observed-future target. Changing
the gate must not silently change the confusion-matrix denominator or truth.
No fitting, traffic, runtime changes, model selection or promotion occurs.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections import Counter
from dataclasses import replace
from pathlib import Path
from typing import Any, Dict

import predictive_sla_validation as v1
import predictive_sla_validation_v3 as v3
import predictive_sla_damped_replay as replay
from backtest_sla_risk import _actual_future_outcome, _classification_block, _ratio, _update_confusion
from qos_damped_holt import QosDampedHoltModel
from qos_holt import QosHoltModel
from sla_episode_evaluation import evaluate_episodes
from sla_risk import SLA_RISK_EVENT_TYPE, SlaRiskPersistence, SlaRiskPolicy, evaluate_sla_forecast


ROOT = Path(__file__).resolve().parent
SCHEMA = "comas-predictive-sla-horizon-sensitivity/1"
CODE_FILES = (*v3.CODE_FILES, "predictive_sla_horizon_sensitivity.py")
VARIANTS = (2, 1)
LIMITATIONS = [
    "The inspected v3 failures motivated this post-hoc sensitivity study; it is not an independent prospective test.",
    "Only required_consecutive_horizons changes; models, calibrated intervals, threshold, persistence and episode rules remain frozen.",
    "Both gates are scored against the official two-horizon observed-future window labels, not variant-specific labels.",
    "Window labels and sustained episodes are different targets; a window FP is not necessarily an unmatched episode activation.",
    "A weaker raw gate need not improve strict new-activation anticipation: earlier, duplicate or persistent alerts can change matching.",
    "Lead times are conditional on anticipated episodes; paired losses/gains, late, unmatched and control activations must also be examined.",
    "Correlated ports, windows, episodes and repeated profiles do not establish independent samples or statistical superiority.",
    "No variant is selected or promoted; any proposed rule change requires a new prospectively frozen validation campaign.",
    "No new traffic, refitting, recalibration, live risk publication, LLM consultation or preventive actuation is performed.",
]


def code_snapshot() -> Dict[str, str]:
    return {name: v1.digest_file(ROOT / name) for name in CODE_FILES}


def output_path(protocol_path: Path, requested: Path) -> Path:
    """Only a new diagnostic JSON directly beside the existing v3 protocol."""
    absolute, resolved = requested.absolute(), requested.resolve()
    if absolute.is_symlink() or resolved.exists():
        raise ValueError("saída já existe ou é link simbólico; use outro nome")
    if (resolved.parent != protocol_path.resolve().parent
            or not resolved.name.startswith("horizon-sensitivity") or resolved.suffix != ".json"):
        raise ValueError("use novo horizon-sensitivity*.json diretamente no diretório do protocolo v3")
    return resolved


def _snapshot(protocol: Dict[str, Any], path: Path, campaign: Path,
              official: Dict[str, Any]) -> Dict[str, str]:
    files = {Path(p) for p in protocol["protected_source_sha256"]}
    files.update(Path(p) for p in official["source_sha256"])
    files.update(path.parent / entry["path"] for entry in protocol["models"].values())
    files.update((path, campaign / "campaign-summary.json"))
    plan = campaign / "campaign-plan.json"
    if plan.exists():
        files.add(plan)
    return {str(p.resolve()): v1.digest_file(p) for p in sorted(files)}


def _risk_policy(model: QosHoltModel, settings: Dict[str, Any]) -> SlaRiskPolicy:
    return SlaRiskPolicy(metric=model.metric, comparator="MAX", threshold=settings["threshold"],
                         horizons_steps=tuple(h.horizon_steps for h in model.horizons),
                         required_consecutive_horizons=settings["required_consecutive_horizons"])


def replay_gate(model: QosHoltModel, series: Dict[str, Any], baseline: Dict[str, Any],
                settings: Dict[str, Any], required: int) -> Dict[str, Any]:
    """Re-gate verified past-only forecasts; future values are used only to score.

    The cached rows have already been regenerated by the unchanged official v3
    evaluator. They retain its priming/tail scope and frozen labels.
    """
    if required not in VARIANTS or settings != v3.POLICY:
        raise ValueError("a análise permite somente os gates 2/1 com a política v3 congelada")
    variant_settings = {**settings, "required_consecutive_horizons": required}
    gate_policy, truth_policy = _risk_policy(model, variant_settings), _risk_policy(model, settings)
    state = SlaRiskPersistence(activation_windows=settings["activation_windows"], clear_windows=settings["clear_windows"])
    maximum = max(gate_policy.horizons_steps)
    values, timestamps = series["values"], series["timestamps_ns"]
    rows, observations = [], []
    candidate_counts, active_counts, decisions, risks = Counter(), Counter(), Counter(), Counter()
    watch_positive = watch_negative = activations = clears = 0
    flat = replay.structural_property(model, variant_settings)
    for cached in baseline["rows"]:
        index = cached["index"]
        if cached["ts_ns"] != timestamps[index] or cached["observed_value"] != values[index]:
            raise ValueError("janela verificada não corresponde à série observada")
        evaluation = evaluate_sla_forecast(
            policy=gate_policy, cid=series["cid"], subject_type="port", subject_id=series["port_id"],
            observed_value=values[index], window_id=index + 1, observation_ns=timestamps[index],
            sample_interval_s=model.sample_interval_s, forecasts=cached["predictions"],
            model_id=model.resolved_model_id(), model_type=model.model_type,
            created_ns=timestamps[index], ttl_s=maximum * model.sample_interval_s)
        if evaluation["forecast"]["horizons"] != cached["predictions"]:
            raise ValueError("gate alterou as previsões ou os intervalos congelados")
        persistent = state.update(evaluation)
        # Always the original two-horizon truth, NEVER gate_policy for rule 1.
        actual = _actual_future_outcome(values, index, truth_policy)
        if actual["positive"] != cached["actual_positive"] or actual["values"] != cached["actual_horizons"]:
            raise ValueError("rótulos observados divergem do alvo oficial v3")
        decision = evaluation["decision"]
        candidate, active = decision == SLA_RISK_EVENT_TYPE, bool(persistent["active"])
        if required == 1 and cached["candidate"] and not candidate:
            raise ValueError("gate de um horizonte perdeu um candidato bruto de dois horizontes")
        activation = bool(persistent["transitioned"] and active)
        clear = bool(persistent["transitioned"] and not active)
        _update_confusion(candidate_counts, candidate, actual["positive"])
        _update_confusion(active_counts, active, actual["positive"])
        decisions[decision] += 1
        risks[evaluation["risk"]["level"]] += 1
        if decision == "WATCH":
            watch_positive += actual["positive"]
            watch_negative += not actual["positive"]
        activations += activation
        clears += clear
        observations.append(dict(index=index, persistent_activation=activation))
        rows.append({**cached, "decision": decision, "candidate": candidate, "active": active,
                     "activation": activation, "clear_transition": clear})
    episodes = evaluate_episodes(
        values=values, observations=observations, timestamps_ns=timestamps,
        series_id=series["series_id"], cid=series["cid"], port_id=series["port_id"], comparator="MAX",
        threshold=settings["threshold"], sample_interval_s=model.sample_interval_s,
        max_horizon_steps=maximum, min_breach_samples=settings["episode_min_breach_samples"],
        clear_samples=settings["episode_clear_samples"])
    block = {**baseline, "rows": rows, "candidate": _classification_block(candidate_counts),
             "persistent_active": {**_classification_block(active_counts), "activation_transitions": activations,
                                   "clear_transitions": clears},
             "decision_counts": dict(sorted(decisions.items())), "risk_level_counts": dict(sorted(risks.items())),
             "watch_only": dict(windows=decisions["WATCH"], rate=_ratio(decisions["WATCH"], len(rows)),
                                future_positive_windows=watch_positive, future_negative_windows=watch_negative,
                                precision=_ratio(watch_positive, watch_positive + watch_negative)),
             "episode_events": episodes, "late_activations": replay._late_activations(episodes),
             "structural_diagnostics": {**baseline["structural_diagnostics"],
                 "short_horizons_flat_identical": flat, "checked_windows": len(rows) if flat else 0,
                 "candidates_before_first_observed_breach": sum(
                     r["candidate"] and r["before_first_observed_breach"] for r in rows)}}
    if required == 2 and block != baseline:
        raise ValueError("baseline de dois horizontes não reproduz integralmente o relatório oficial v3")
    replay.paired_changes([baseline], [block])  # Includes observed episode eligibility/censoring.
    return block


def _pair(two: list, one: list) -> Dict[str, Any]:
    pair = replay.paired_changes(two, one)
    # The comparison is a gate change within one model, not a trained-model comparison.
    pair["paired_episodes"] = [dict(
        episode_id=e["episode_id"], eligible=e["eligible"], onset_ts_ns=e["onset_ts_ns"],
        two_horizons_anticipated=e["original_anticipated"], one_horizon_anticipated=e["trained_anticipated"],
        two_horizons_lead_s=e["original_lead_s"], one_horizon_lead_s=e["trained_lead_s"])
        for e in pair["paired_episodes"]]
    a, b = replay.aggregate(two), replay.aggregate(one)
    pair["delta_one_minus_two"] = {field: b[field] - a[field] for field in (
        "anticipated", "missed", "total_activations", "control_activations", "unmatched_activations",
        "censored_activations", "late_activations", "watch_windows")}
    pair["delta_one_minus_two"]["window_FP"] = b["candidate"]["confusion"]["FP"] - a["candidate"]["confusion"]["FP"]
    return pair


def study(protocol_path: Path, campaign: Path) -> Dict[str, Any]:
    path = protocol_path.resolve()
    campaign = v3.campaign_path(path, campaign)
    p = v3.load_protocol(path)
    official = json.loads((campaign / "campaign-summary.json").read_text(encoding="utf-8"))
    before, code = _snapshot(p, path, campaign, official), code_snapshot()
    verified = v3.evaluate_campaign(path, campaign)
    if (verified["status"] != "COMPLETED" or verified["evaluated_runs"] != 12 or official != verified):
        raise ValueError("campanha/relatório oficial v3 incompleto ou divergente; nenhum diagnóstico será publicado")
    artifacts = {}
    for name, entry in p["models"].items():
        artifact = (QosDampedHoltModel if name == v3.PRIMARY else QosHoltModel).load(path.parent / entry["path"])
        artifacts[name] = replace(artifact, model_id=artifact.resolved_model_id())
    blocks = {name: {n: [] for n in VARIANTS} for name in artifacts}
    for case, result in zip(p["cases"], verified["cases"]):
        series, record, hashes = v1._read_case(p, case, campaign / case["case_id"])
        if (result["case_id"] != case["case_id"] or result["source_sha256"] != hashes
                or result["run_sha256"] != record["run_sha256"]):
            raise ValueError("fontes novas mudaram após a verificação v3")
        for name, model in artifacts.items():
            for item, baseline in zip(series, result["models"][name]["series"]):
                for required in VARIANTS:
                    blocks[name][required].append(replay_gate(model, item, baseline, p["policy"], required))
    models = {}
    for name, variants in blocks.items():
        summaries = {n: v3._summarize(items, verified["cases"]) for n, items in variants.items()}
        if summaries[2] != verified["models"][name]:
            raise ValueError("agregado de dois horizontes diverge do baseline oficial v3")
        models[name] = dict(model_id=p["models"][name]["model_id"], model_sha256=p["models"][name]["sha256"],
            variants={f"consecutive{n}": dict(policy={**p["policy"], "required_consecutive_horizons": n},
                                             summary=summaries[n], series=variants[n]) for n in VARIANTS},
            paired_changes=_pair(variants[2], variants[1]))
    if _snapshot(p, path, campaign, official) != before or code_snapshot() != code:
        raise ValueError("fontes/código mudaram durante a análise; nenhum diagnóstico será publicado")
    return v1.seal(dict(
        schema_version=SCHEMA, status="SENSITIVITY_COMPLETED", scope="post_hoc_v3_gate_sensitivity",
        independent_test=False, promotion_eligible=False, deployment_eligible=False, selected_variant="NONE",
        refit=False, recalibration=False, statistical_superiority_assessed=False,
        new_traffic=False, llm_consulted=False, evaluation_unit=v3.EVALUATION_UNIT,
        protocol_path=str(path), protocol_sha256=p["protocol_sha256"], campaign_root=str(campaign),
        official_v3=dict(status=official["status"], criteria_status=official["criteria_status"], checks=official["checks"],
                         evaluated_runs=official["evaluated_runs"], planned_runs=official["planned_runs"],
                         report_sha256=official["report_sha256"], summary_file_sha256=before[str(campaign / "campaign-summary.json")]),
        official_v3_unchanged=True, baseline_exact=True, point_forecasts_identical=True, intervals_identical=True,
        scoring_scope_identical=True, observed_future_labels_identical=True, observed_episode_ground_truth_identical=True,
        identity_scope="within_each_frozen_model_between_gates; not_between_models",
        scoring_target=dict(window="frozen_v3_two_adjacent_observed_future_horizons",
                            policy=p["policy"], episodes="unchanged_sustained_episodes_with_strict_timestamp_matching"),
        models=models, protected_source_sha256=before, code_sha256=code,
        git_commit=subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip(),
        limitations=LIMITATIONS), "report_sha256")


def print_summary(report: Dict[str, Any]) -> None:
    print(f"official_v3={report['official_v3']['status']} criteria={report['official_v3']['criteria_status']} "
          f"unchanged={str(report['official_v3_unchanged']).lower()} baseline_exact={str(report['baseline_exact']).lower()}")
    for name in (v3.REFERENCE, v3.PRIMARY):
        model = report["models"][name]
        for required in VARIANTS:
            s = model["variants"][f"consecutive{required}"]["summary"]
            lead = s["lead_time_s"]["mean"]
            lead_text = "N/A" if lead is None else f"{lead:.3f}s"
            print(f"{name} horizons={required}: anticipated={s['anticipated']}/{s['eligible_episodes']} "
                  f"late={s['late_activations']} control={s['control_activations']} unmatched={s['unmatched_activations']} "
                  f"censored={s['censored_activations']} FP={s['candidate']['confusion']['FP']} "
                  f"WATCH={s['watch_windows']} lead={lead_text}")
        paired = model["paired_changes"]
        print(f"{name} paired: lost={len(paired['lost_anticipated_episodes'])} "
              f"gained={len(paired['gained_anticipated_episodes'])} fixed_truth=true")
    print("status=SENSITIVITY_COMPLETED selected_variant=NONE promotion_eligible=false independent_test=false")


def main(argv: list | None = None) -> int:
    parser = argparse.ArgumentParser(description="Sensibilidade offline dos gates de um/dois horizontes nos dados v3")
    parser.add_argument("--protocol", type=Path, required=True)
    parser.add_argument("--campaign-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        target = output_path(args.protocol, args.output)
        report = study(args.protocol, args.campaign_root)
        v1.write_new_json(target, report)
        print_summary(report)
        return 0  # Diagnostic completion is not approval of the official criteria.
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print(f"erro: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
